services:
  - type: web
    name: roomtn-backend
    env: node
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://saifyedes20:Sayfountahfoun2001@cluster0.iupdulh.mongodb.net/roomtn?retryWrites=true&w=majority&appName=Cluster0
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 10000